language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - "node_modules"
script: 
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls
