language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - "node_modules"
env:
  global:
    - DATABASE_URL_TEST=postgres://postgres@127.0.0.1:5432/test
     - CXX=g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script: 
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8